### ISSUE TITLE
which version of original ray is best compatible with the custom ray package?

### ISSUE THREAD

**Issue by TianChenone** [natashamjaques/ray#3]
when I  replace the content of 'rllib, autoscaler and tune' of the original ray package with the custom ray package, there are lots of problems relating to compatibility. 
my environment setting:
ubuntu 16.04 python 3.6.7 ray(0.6.1/0.7.2 both two versions have been tried) tensorflow-gpu 1.12.0 
the errors are quite like 

ImportError while importing test module '/home/wsw/cyt_DRL/paper_code/sequential_social_dilemma_games-master/ray/python/ray/tests/test_actor.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../../../anaconda2/envs/causal/lib/python3.6/site-packages/ray/tests/test_actor.py:20: in 
from ray.tests.utils import (
E ImportError: cannot import name 'relevant_errors'
_____________ ERROR collecting ray/python/ray/tests/test_array.py ______________
import file mismatch:
imported module 'ray.tests.test_array' has this file attribute:
/home/wsw/anaconda2/envs/causal/lib/python3.6/site-packages/ray/tests/test_array.py
which is not the same as the test file we want to collect:
/home/wsw/cyt_DRL/paper_code/sequential_social_dilemma_games-master/ray/python/ray/tests/test_array.py
HINT: remove pycache / .pyc files and/or use a unique basename for your test file modules
____________ ERROR collecting ray/python/ray/tests/test_cython.py _____________
ImportError while importing test module '/home/wsw/cyt_DRL/paper_code/sequential_social_dilemma_games-master/ray/python/ray/tests/test_cython.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../../../anaconda2/envs/causal/lib/python3.6/site-packages/ray/tests/test_cython.py:9: in 
import cython_examples as cyth
E ModuleNotFoundError: No module named 'cython_examples'
...........

Could you give some information about the original ray version where you do some modification base on ? 
Thank you very much!

**Comment by natashamjaques** [comment]
Hi! Thanks for your question. We have recently discovered several serious bugs in ray that would have prevented the causal influence code implemented here from working correctly, including one in which the inputs to the LSTM were being scrambled. Therefore, we are no longer planning to use the code in this fork or planning on supporting it.
